export { default as Icons } from './Icons'
export { default as Navbar } from './Navbar'
export { default as Page2Icons } from './Page2Icons'
export { default as Codebtn } from './Codebtn'
export { default as GettingStartedBtn } from './GettingStartedBtn'
export { default as Page3Icons } from './Page3Icons'
