export { default as Icons } from './Icons'
export { default as Navbar } from './Navbar'
export { default as Page2Icons } from './Page2Icons'
export { default as Codebtn } from './Codebtn'
export { default as Page3Icons } from './Page3Icons'
export { default as Btn } from './Btn'
export { default as Footer } from './Footer'
